name: 'Setup virtualenv'
description: 'Setup a cached virtualenv. Only installs dependencies, not the code'
inputs:
  venv-path:
    description: Path of venv
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup venv
      shell: bash
      run: |
        python3 -m venv .venv
        .venv/bin/pip install "poetry>=1.8.2<2"
        .venv/bin/poetry install --with dev --no-root
