name: "Build dataset site"
on:
  workflow_run:
    workflows: [Test and Lint]
    types:
      - completed
  pull_request:
    paths:
      - 'content/**'
      - '.github/worklows/build_site.yml'
  push:
    branches:
    - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    env:
        PYTHONPATH: "lib/:${PYTHONPATH}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup virtualenv 
        uses: ./.github/actions/setup-venv
        with:
          venv-path: .venv
      
      - name: Run build
        run: .venv/bin/python3 -m dsets build
        
      
      
