name: "Test and Lint"
on:
  pull_request:
    paths:
      - 'content/**'
      - 'lib/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/worklows/test_lint.yml'
  push:
    branches:
    - main

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    env:
        PYTHONPATH: "lib/:${PYTHONPATH}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup virtualenv 
        uses: ./.github/actions/setup-venv
        with:
          venv-path: .venv

      - name: Check poetry.lock
        run: .venv/bin/python3 -m poetry lock --check

      - name: Run formatters
        run: |
          .venv/bin/python3 -m ruff check lib/
          .venv/bin/python3 -m ruff format --check lib/

      - name: Run tests
        run: .venv/bin/python3 -m pytest lib/tests/

      - name: Run build
        run: .venv/bin/python3 -m dsets build
      
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: ./_build
          key: ${{ github.sha }}
  
  push_build:
    needs: lint_test_build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging]
    env:
        PYTHONPATH: "lib/:${PYTHONPATH}"
        BUCKET_NAME: ${{ secrets.CONTENT_BUCKET_NAME }}
        BUCKET_PUBLIC_DOMAIN_NAME: ${{ secrets.BUCKET_PUBLIC_DOMAIN_NAME }}

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup virtualenv 
        uses: ./.github/actions/setup-venv
        with:
          venv-path: .venv
      
      - name: Restore cached build
        id: restore-build
        uses: actions/cache/restore@v4
        with:
          path: ./_build
          key: ${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      


