name: "Test and lint lib"
on:
  pull_request:
    paths:
      - 'lib/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/**'
  push:
    branches:
    - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    env:
        PYTHONPATH: "lib/:${PYTHONPATH}"
        POETRY_VIRTUALENVS_CREATE: "false"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup virtualenv 
        uses: ./.github/actions/setup-venv
        with:
          venv-path: .venv

      - name: Check poetry.lock
        run: .venv/bin/poetry lock --check

      - name: Run formatters
        run: |
          .venv/bin/poetry run ruff check lib/
          .venv/bin/poetry run ruff format --check lib/

      - name: Run tests
        run: .venv/bin/poetry run pytest lib/tests/
